<a href="https://colab.research.google.com/github/Vicodwer/Day_25/blob/main/Day_25_AM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd

df =pd.read_csv("/content/youtube_data.csv")

# Part-1

Basic Exploration

In [5]:
df.head()

,video_id,title,description,published_date,channel_id,channel_title,tags,category_id,view_count,like_count,comment_count,duration,thumbnail
0,gsJAlLOFBv0,TINY Tech That Actually Works,No description available,2025-05-02T17:37:10Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['tiny', 'tech', 'gadgets', 'small', 'miniature']",28,8962092.0,243350.0,515.0,PT57S,https://i.ytimg.com/vi/gsJAlLOFBv0/default.jpg
1,ypicIkaiViM,AI & future of workforce: Andrew Yang on how t...,"Andrew Yang, Forward Party co-chair and former...",2025-06-18T12:39:53Z,UCrp_UI8XtuYfpiqluWLD7Lw,CNBC Television,"['Squawk Box U.S.', 'CNBC', 'business news', '...",25,289626.0,3393.0,1240.0,PT7M50S,https://i.ytimg.com/vi/ypicIkaiViM/default.jpg
2,1Nef8LPO-jo,5 ILLEGAL gadgets that will get you ARRESTED,#shorts #technology \n\nI spend a LOT of time ...,2022-11-01T11:00:06Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech']",28,81372201.0,4178447.0,6378.0,PT47S,https://i.ytimg.com/vi/1Nef8LPO-jo/default.jpg
3,lCHqmzynO-s,Overrated vs. Underrated Tech,💬 Join my Discord server: https://discord.gg/g...,2024-07-08T18:04:31Z,UCPk2s5c4R_d-EUUNvFFODoA,Gohar Khan,"['thailand', 'surin', 'style', 'travel', 'day'...",27,21255964.0,909386.0,2681.0,PT31S,https://i.ytimg.com/vi/lCHqmzynO-s/default.jpg
4,7uFrtqSwYzM,APPLE Glass Revolutionizes AR Experience Forever!,Discover the revolutionary world of augmented ...,2024-12-22T16:49:00Z,UCxqG_E-68WAE0TWYfIopv6Q,Digifix,"['apple glasses price', 'apple glasses design'...",28,2790436.0,44278.0,1359.0,PT16S,https://i.ytimg.com/vi/7uFrtqSwYzM/default.jpg

In [6]:
df.tail()

,video_id,title,description,published_date,channel_id,channel_title,tags,category_id,view_count,like_count,comment_count,duration,thumbnail
595,jWiV4bWsDl4,Puse a prueba estos rayos x para ver a traves ...,Canal principal: https://www.youtube.com/c/Pon...,2022-05-03T22:23:10Z,UCPx9eXszFK8rkivV7tXZpHA,PONGAMOSLO A PRUEBA CORTOS,"['walabot', 'ver tubos en las paredes', 'ver m...",24,15631786.0,1692338.0,4662.0,PT1M,https://i.ytimg.com/vi/jWiV4bWsDl4/default.jpg
596,pGtMbnxaXs8,Old Tech That Still Works #facts #sciencefact...,🕹️ Old Tech That Still Works – Built to Last!\...,2025-06-20T05:15:19Z,UCetvIcfQ5MfL1B_3oebxbAA,Nice Channel,"['thailand', 'surin', 'style', 'travel', 'day'...",20,616.0,7.0,1.0,PT48S,https://i.ytimg.com/vi/pGtMbnxaXs8/default.jpg
597,2DaOJ1a0AYg,iPhone lene vale ho to ruk jao #smartphone #s2...,No description available,2025-06-19T13:39:44Z,UCsVgd6S420V16aJmVcNNSYQ,Killer tech,"['thailand', 'surin', 'style', 'travel', 'day'...",27,15534.0,70.0,12.0,PT10S,https://i.ytimg.com/vi/2DaOJ1a0AYg/default.jpg
598,aO5HE6Q0jaM,Programming memes 😂 sub for more 🖥️👾#tech #tec...,No description available,2025-06-20T02:00:02Z,UCO6cVKP66LTeHkoA6lD8CYA,Programming Nerd,"['thailand', 'surin', 'style', 'travel', 'day'...",22,4223.0,182.0,5.0,PT6S,https://i.ytimg.com/vi/aO5HE6Q0jaM/default.jpg
599,Ukb8U5Ku4gA,Amazing Power Full Tractor Work In The Field ...,No description available,2025-06-19T15:16:47Z,UCi9qNcs4B_Ow1BEfCBKKaoQ,Funny Truck,"['thailand', 'surin', 'style', 'travel', 'day'...",22,198486.0,573.0,0.0,PT6S,https://i.ytimg.com/vi/Ukb8U5Ku4gA/default.jpg

In [7]:
df.shape

(600, 13)

In [8]:
df.columns

Index(['video_id', 'title', 'description', 'published_date', 'channel_id',
       'channel_title', 'tags', 'category_id', 'view_count', 'like_count',
       'comment_count', 'duration', 'thumbnail'],
      dtype='object')

Data Cleaning

In [9]:
df.isnull().sum()

video_id          0
title             0
description       0
published_date    0
channel_id        0
channel_title     0
tags              0
category_id       0
view_count        0
like_count        0
comment_count     0
duration          0
thumbnail         0
dtype: int64

In [11]:
df_filled = df.fillna(df.mean(numeric_only = True))

Descriptive Statistics

In [12]:
df.describe()

       category_id    view_count    like_count  comment_count
count   600.000000  6.000000e+02  6.000000e+02     600.000000
mean     24.903333  8.080299e+06  2.174646e+05    1970.144781
std       4.863477  2.455377e+07  5.074207e+05    4421.455908
min       1.000000  3.120000e+02  0.000000e+00       0.000000
25%      22.000000  8.150100e+04  1.646000e+03      13.000000
50%      27.000000  9.587180e+05  2.214900e+04     252.500000
75%      28.000000  5.991357e+06  2.174646e+05    1802.500000
max      30.000000  3.437590e+08  4.421091e+06   40241.000000

 Interpretation of describe():
Mean → Average value
Min → Smallest value
Max → Largest value
Std → Standard deviation (spread of data)

Example Insight (YouTube dataset):

If average views = 500,000 → Typical video gets 500K views.
High std → Views vary a lot.
Max >> Mean → Some viral videos exist.

Categorical Analysis

In [14]:
df['category_id'].unique()

array([28, 25, 27, 24, 19, 10, 22, 23, 26, 29, 20,  1, 15,  2, 17, 30])

In [15]:
df['category_id'].value_counts()

category_id
28    284
22     94
27     57
24     50
23     22
20     21
25     17
10     14
26     10
15      7
2       6
19      5
17      4
1       4
30      3
29      2
Name: count, dtype: int64

# Part- B

Filter Dataset with Multiple Conditions

In [18]:
filtered_df = df[(df['view_count']>100000) & (df['like_count']> 10000)]
filtered_df.head()

,video_id,title,description,published_date,channel_id,channel_title,tags,category_id,view_count,like_count,comment_count,duration,thumbnail
0,gsJAlLOFBv0,TINY Tech That Actually Works,No description available,2025-05-02T17:37:10Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['tiny', 'tech', 'gadgets', 'small', 'miniature']",28,8962092.0,243350.0,515.0,PT57S,https://i.ytimg.com/vi/gsJAlLOFBv0/default.jpg
2,1Nef8LPO-jo,5 ILLEGAL gadgets that will get you ARRESTED,#shorts #technology \n\nI spend a LOT of time ...,2022-11-01T11:00:06Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech']",28,81372201.0,4178447.0,6378.0,PT47S,https://i.ytimg.com/vi/1Nef8LPO-jo/default.jpg
3,lCHqmzynO-s,Overrated vs. Underrated Tech,💬 Join my Discord server: https://discord.gg/g...,2024-07-08T18:04:31Z,UCPk2s5c4R_d-EUUNvFFODoA,Gohar Khan,"['thailand', 'surin', 'style', 'travel', 'day'...",27,21255964.0,909386.0,2681.0,PT31S,https://i.ytimg.com/vi/lCHqmzynO-s/default.jpg
4,7uFrtqSwYzM,APPLE Glass Revolutionizes AR Experience Forever!,Discover the revolutionary world of augmented ...,2024-12-22T16:49:00Z,UCxqG_E-68WAE0TWYfIopv6Q,Digifix,"['apple glasses price', 'apple glasses design'...",28,2790436.0,44278.0,1359.0,PT16S,https://i.ytimg.com/vi/7uFrtqSwYzM/default.jpg
5,THw-wXt7wyM,5 Tech Myths Busted!,#shorts \n\nI spend a LOT of time trying to ma...,2022-10-02T19:40:14Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech', 'myths', 'busted', 'tips']",28,28131104.0,1956461.0,6253.0,PT56S,https://i.ytimg.com/vi/THw-wXt7wyM/default.jpg

Create New Column

In [19]:
df['Engagement_Rate'] = (df['like_count'] / df['view_count'])  * 100
df.head()

,video_id,title,description,published_date,channel_id,channel_title,tags,category_id,view_count,like_count,comment_count,duration,thumbnail,Engagement_Rate
0,gsJAlLOFBv0,TINY Tech That Actually Works,No description available,2025-05-02T17:37:10Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['tiny', 'tech', 'gadgets', 'small', 'miniature']",28,8962092.0,243350.0,515.0,PT57S,https://i.ytimg.com/vi/gsJAlLOFBv0/default.jpg,2.715326
1,ypicIkaiViM,AI & future of workforce: Andrew Yang on how t...,"Andrew Yang, Forward Party co-chair and former...",2025-06-18T12:39:53Z,UCrp_UI8XtuYfpiqluWLD7Lw,CNBC Television,"['Squawk Box U.S.', 'CNBC', 'business news', '...",25,289626.0,3393.0,1240.0,PT7M50S,https://i.ytimg.com/vi/ypicIkaiViM/default.jpg,1.171511
2,1Nef8LPO-jo,5 ILLEGAL gadgets that will get you ARRESTED,#shorts #technology \n\nI spend a LOT of time ...,2022-11-01T11:00:06Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech']",28,81372201.0,4178447.0,6378.0,PT47S,https://i.ytimg.com/vi/1Nef8LPO-jo/default.jpg,5.134981
3,lCHqmzynO-s,Overrated vs. Underrated Tech,💬 Join my Discord server: https://discord.gg/g...,2024-07-08T18:04:31Z,UCPk2s5c4R_d-EUUNvFFODoA,Gohar Khan,"['thailand', 'surin', 'style', 'travel', 'day'...",27,21255964.0,909386.0,2681.0,PT31S,https://i.ytimg.com/vi/lCHqmzynO-s/default.jpg,4.278263
4,7uFrtqSwYzM,APPLE Glass Revolutionizes AR Experience Forever!,Discover the revolutionary world of augmented ...,2024-12-22T16:49:00Z,UCxqG_E-68WAE0TWYfIopv6Q,Digifix,"['apple glasses price', 'apple glasses design'...",28,2790436.0,44278.0,1359.0,PT16S,https://i.ytimg.com/vi/7uFrtqSwYzM/default.jpg,1.586777

Sort Dataset

In [21]:
df_sorted = df.sort_values(by='view_count', ascending = False)
df_sorted.head()

,video_id,title,description,published_date,channel_id,channel_title,tags,category_id,view_count,like_count,comment_count,duration,thumbnail,Engagement_Rate
438,5RDSkR8_AQ0,50 Cent - Ayo Technology (Official Music Video...,REMASTERED IN HD!\nOfficial Music Video for Ay...,2009-06-17T05:30:22Z,UC0sL86jDLgs2fGRD-XBnPQA,50CentVEVO,"['50 CENT', '50 CENT AYO TECHNOLOGY', 'AYO TEC...",10,343758991.0,1734503.0,40241.0,PT4M9S,https://i.ytimg.com/vi/5RDSkR8_AQ0/default.jpg,0.504569
163,h0xOdfMJTJI,This is future technology 2d animation #shorts,No description available,2022-05-27T07:07:04Z,UCOvOXLATfCrOJmAYaO4mRBA,VFX HD,"['thailand', 'surin', 'style', 'travel', 'day'...",1,246090760.0,2148424.0,1109.0,PT13S,https://i.ytimg.com/vi/h0xOdfMJTJI/default.jpg,0.873021
59,-055GvEU7f0,Worlds smallest 4K headset 😎 Visor.com #tech #...,Visor is the world's smallest 4K headset. Spaw...,2024-06-21T14:12:54Z,UCGmuLwV0XD_uqL4wKZg4hgA,Immersed,"['thailand', 'surin', 'style', 'travel', 'day'...",28,208897321.0,4130446.0,7065.0,PT15S,https://i.ytimg.com/vi/-055GvEU7f0/default.jpg,1.977261
79,IPhARlUO6NA,New Science Project #shorts #science #technolo...,New Science Project #shorts #science #technolo...,2023-04-28T01:30:04Z,UChvzFAyWyofbidb7Mh3WMZw,VMK Technical Power,"['shorts', 'science', 'technology', 'trending']",28,161748042.0,4421091.0,8794.0,PT15S,https://i.ytimg.com/vi/IPhARlUO6NA/default.jpg,2.733320
184,Oyc9c1q0RRU,Free motion setup in progress | Techwala | Des...,Free motion in progress | Techwala | Desi perp...,2024-04-21T13:45:01Z,UCGza0UwOOdcryLK-1taT8SA,Techवाला,"['perpetu motion machine', 'free energy machin...",28,139303650.0,1474630.0,16759.0,PT11S,https://i.ytimg.com/vi/Oyc9c1q0RRU/default.jpg,1.058572

Group Data & Compute Mean

In [23]:
grouped = df.groupby('category_id')['view_count'].mean()
grouped

category_id
1     6.426066e+07
2     1.341963e+05
10    3.297006e+07
15    6.418300e+04
17    9.497400e+04
19    2.699663e+06
20    3.727255e+05
22    8.214729e+06
23    3.023124e+06
24    8.606462e+06
25    3.579913e+06
26    6.280858e+06
27    2.773119e+06
28    8.837065e+06
29    1.093886e+07
30    8.080299e+06
Name: view_count, dtype: float64

# Part-C

Q1 — What is EDA? Why is it important?

Exploratory Data Analysis (EDA) is the process of analyzing datasets to understand their structure, patterns, distributions, anomalies, and relationships before applying machine learning models.

Why Important?
Detects missing values
Identifies outliers
Understands feature distributions
Guides feature engineering
Prevents garbage-in garbage-out problem

Q2--Coding Question
Filter rows where column value > average

In [24]:
average_views = df['view_count'].mean()

above_avg = df[df['view_count'] > average_views]
above_avg.head()

,video_id,title,description,published_date,channel_id,channel_title,tags,category_id,view_count,like_count,comment_count,duration,thumbnail,Engagement_Rate
0,gsJAlLOFBv0,TINY Tech That Actually Works,No description available,2025-05-02T17:37:10Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['tiny', 'tech', 'gadgets', 'small', 'miniature']",28,8962092.0,243350.0,515.0,PT57S,https://i.ytimg.com/vi/gsJAlLOFBv0/default.jpg,2.715326
2,1Nef8LPO-jo,5 ILLEGAL gadgets that will get you ARRESTED,#shorts #technology \n\nI spend a LOT of time ...,2022-11-01T11:00:06Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech']",28,81372201.0,4178447.0,6378.0,PT47S,https://i.ytimg.com/vi/1Nef8LPO-jo/default.jpg,5.134981
3,lCHqmzynO-s,Overrated vs. Underrated Tech,💬 Join my Discord server: https://discord.gg/g...,2024-07-08T18:04:31Z,UCPk2s5c4R_d-EUUNvFFODoA,Gohar Khan,"['thailand', 'surin', 'style', 'travel', 'day'...",27,21255964.0,909386.0,2681.0,PT31S,https://i.ytimg.com/vi/lCHqmzynO-s/default.jpg,4.278263
5,THw-wXt7wyM,5 Tech Myths Busted!,#shorts \n\nI spend a LOT of time trying to ma...,2022-10-02T19:40:14Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['shorts', 'tech', 'myths', 'busted', 'tips']",28,28131104.0,1956461.0,6253.0,PT56S,https://i.ytimg.com/vi/THw-wXt7wyM/default.jpg,6.954796
7,LZYfSYXY-go,Apple’s THINNEST ever device is RIDICULOUS!,#shorts #tech #gadgets #apple #iphone \n\nI s...,2024-01-04T15:32:23Z,UCMiJRAwDNSNzuYeN2uWa0pA,Mrwhosetheboss,"['apple', 'iphone', 'tech', 'gadgets', 'shorts...",28,17538777.0,835009.0,3583.0,PT30S,https://i.ytimg.com/vi/LZYfSYXY-go/default.jpg,4.760931

Q3 — What insights can we get from describe()?

describe() gives:

Count → Number of non-null values
Mean → Central tendency
Std → Variability
Min & Max → Range
25%, 50%, 75% → Quartiles
Insights:
Detect skewness (mean vs median difference)
Identify outliers (max far from 75%)
Understand spread of data
Compare feature scales

# Part- D

Prompt Used:

"Explain EDA steps using Pandas with examples."

AI Output (Documented)

EDA using Pandas involves:

Loading data using pd.read_csv()
Exploring structure using head(), tail(), shape, columns
Checking missing values using isnull()
Cleaning data using dropna() or fillna()
Generating statistics using describe()
Analyzing categories using value_counts()
Filtering and grouping using groupby()

In [27]:
# example used :
df = pd.read_csv("/content/youtube_data.csv")
df.head()
df.describe()
df.isnull().sum()
df.groupby('category_id')['view_count'].mean()

category_id
1     6.426066e+07
2     1.341963e+05
10    3.297006e+07
15    6.418300e+04
17    9.497400e+04
19    2.699663e+06
20    3.727255e+05
22    8.214729e+06
23    3.023124e+06
24    8.606462e+06
25    3.579913e+06
26    6.280858e+06
27    2.773119e+06
28    8.837065e+06
29    1.093886e+07
30    8.080299e+06
Name: view_count, dtype: float64

Evaluation of AI Output

✅ Correctly explains main EDA steps
✅ Includes relevant Pandas functions
✅ Covers cleaning + statistics + grouping
⚠️ Does not deeply interpret statistical meaning

Conclusion: Output is correct but needs human interpretation for business insights.